### ISSUE TITLE
Got Error Streming data

### ISSUE THREAD

**Issue by panux50** [Fitsbit/YoutubeVideoToAIPoweredShorts#1]
try to run YoutubeVideoAI script and got this error

`Enter the YouTube video link: https://www.youtube.com/watch?v=ohyriVQN2sA
Traceback (most recent call last):
  File "YoutubeVideoToAIPoweredShorts.py", line 20, in <module>
    video_stream = youtube.streams.get_highest_resolution()
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'`

i use python 3.6 and have install all the library.

**Comment by Fitsbit** [comment]
Open it up in a code editor something like VSCode and see if you can find any noticeable errors. I'm guessing you'll have todo this because you need to edit where the videos are being saved.


feel free to add comments and questions.

**Comment by Fitsbit** [comment]
Try updating python and make sure you have no errors in the code editor, also try with an English video.

**Comment by bang-soe** [comment]
![Screenshot_2](https://github.com/Fitsbit/YoutubeVideoToAIPoweredShorts/assets/89513375/178dbeed-a2cd-444a-a4ed-160b44776180)
try to running with VS code and get same error. what is your python version?

**Comment by Fitsbit** [comment]
I'm on python 3.11, try doing all your files in a "C" drive not a "D" drive. Script, folders everything. Also try with a popular american/ english video and see if that works.
